# Generated by Django 4.0.3 on 2022-03-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
